apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: hello-2
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-2
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo "Second Cron job triggered !!"
          restartPolicy: OnFailure
