apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  labels:
    name: web-server
spec:
  type: LoadBalancer
  ports:
    # The port that will be exposed by the service.
  - port: 80
  selector:
    app: web-server
