apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 2
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend-container
        image: eu.gcr.io/PROJECT_ID/web:v1
        ports:
        - containerPort: 80
